# --- 1. 主版本 (Stable V1) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zentrix-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zentrix
      version: v1
  template:
    metadata:
      labels:
        app: zentrix
        version: v1
    spec:
      imagePullSecrets: [{name: ghcr-login}]
      containers:
      - name: lab-container
        image: ghcr.io/zentrix566/devops:v1 # 稳定版镜像
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zentrix-v1-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: zentrix
    version: v1
---
# --- 2. 金丝雀版本 (Canary V2) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zentrix-v2-canary
spec:
  replicas: 1 # 金丝雀只需要 1 个副本用来测试
  selector:
    matchLabels:
      app: zentrix
      version: v2
  template:
    metadata:
      labels:
        app: zentrix
        version: v2
    spec:
      imagePullSecrets: [{name: ghcr-login}]
      containers:
      - name: lab-container
        image: ghcr.io/zentrix566/devops:latest # 新版镜像
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zentrix-v2-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: zentrix
    version: v2
---
# --- 3. 金丝雀 Ingress (分流规则) ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zentrix-ingress-canary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"         # ?? 开启金丝雀
    nginx.ingress.kubernetes.io/canary-weight: "10"    # ?? 仅 10% 流量进入 V2
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zentrix-v2-service
            port:
              number: 80
