# --- 1. 稳定版 (V1 - 3个副本) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zentrix-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zentrix
      version: v1
  template:
    metadata:
      labels:
        app: zentrix
        version: v1
    spec:
      imagePullSecrets: [{name: ghcr-login}]
      containers:
      - name: lab-container
        image: ghcr.io/zentrix566/devops:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zentrix-v1-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: zentrix
    version: v1
---
# --- 2. 金丝雀版 (V2 - 1个副本) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zentrix-v2-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zentrix
      version: v2
  template:
    metadata:
      labels:
        app: zentrix
        version: v2
    spec:
      imagePullSecrets: [{name: ghcr-login}]
      containers:
      - name: lab-container
        image: ghcr.io/zentrix566/devops:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zentrix-v2-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: zentrix
    version: v2
---
# --- 3. 流量分发规则 (Ingress) ---
# 主 Ingress：默认所有流量去 V1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zentrix-ingress-main
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zentrix-v1-service
            port:
              number: 80
---
# 金丝雀 Ingress：将 10% 的流量“劫持”到 V2
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zentrix-ingress-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zentrix-v2-service
            port:
              number: 80